---
- name: Simple web-app server
  hosts: all
  vars:
   ansible_host_key_checking: false
  tasks:
    - name: Install "git", "zip", "openjdk-11-jdk"
      apt:
        pkg:
            - git
            - zip
            - openjdk-11-jdk

    - name: Install "SDKMAN!"
      shell: |
        curl -s "https://get.sdkman.io" | bash executable=/bin/bash

    - name: Install "gradle"
      shell: "source /root/.sdkman/bin/sdkman-init.sh && sdk install gradle"

    - name: Clone a github repository
      git:
        repo: https://github.com/Mod4rchive/refactored-train
        dest: /root/refactored-train
        clone: yes
