---
- name: Simple web-app server
  hosts: all
  vars:
   ansible_host_key_checking: false
  tasks:
    - name: Deploy app
      shell: chmod +x ./gradlew|./gradlew bootRun
      args:
        chdir: /root/refactored-train/
